name: Release
on:
  push:
    branches: [ release ]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  release:
    uses: netboxlabs/public-workflows/.github/workflows/reusable-plugin-release.yml@develop
    with:
      plugin_package_name: netboxlabs-netbox-branching
      plugin_package_dir: netbox_branching
      release_notes_from_pr_body: true
    secrets: inherit
